name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            goos: linux
            goarch: amd64
          - os: linux
            arch: arm
            goos: linux
            goarch: arm
          - os: linux
            arch: arm64
            goos: linux
            goarch: arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -v -o wingbits-to-mqtt-${{ matrix.os }}-${{ matrix.arch }} ./...

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wingbits-to-mqtt-${{ matrix.os }}-${{ matrix.arch }}
          path: wingbits-to-mqtt-${{ matrix.os }}-${{ matrix.arch }}

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*
          generate_release_notes: true
