name: Build and Publish wingbits-to-mqtt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20" # Specify the Go version you want to use

      # Cache Go dependencies to speed up builds
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Build the Go service
      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o myservice main.go # Change as per your Go service structure

      # Package the artifact (optional)
      - name: Create release artifact
        run: tar -czf myservice.tar.gz myservice # Adjust the file(s) to be included

      # Upload the artifact to GitHub
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: myservice-artifact
          path: myservice.tar.gz

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Publish the artifact (example: upload to an external service or registry)
      - name: Publish Artifact
        run: |
          # Example: Upload to a remote server or registry
          echo "Publishing the artifact..." # Replace with actual publishing command
          # e.g., using curl, scp, or any other tool to push the artifact to your registry.
