name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            goos: linux
            goarch: amd64
          - os: linux
            arch: arm
            goos: linux
            goarch: arm
            goarm: 7
          - os: linux
            arch: arm64
            goos: linux
            goarch: arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm }}
        run: |
          go build -v -o wingbits-to-mqtt-${{ matrix.os }}-${{ matrix.arch }} ./...

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wingbits-to-mqtt-${{ matrix.os }}-${{ matrix.arch }}
          path: wingbits-to-mqtt-${{ matrix.os }}-${{ matrix.arch }}
          retention-days: 5
